spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: "{cipher}944f391ecd4562b68518a2bc3ad9ee5f1b2ba2fb42bd5f3797c998e5aa588b88"
  jpa:
    properties:
      hibernate:
        show_sql: true

#server:
#  port: 8444
#  ssl:
#    key-store: C:\Users\yyd\mykeys.jks
#    key-store-password: letmein
#    key-password: letmein
management:
  server:
    port: 1112
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always #never，when-authorized

logging:
  config:
    classpath: logback.xml
    path: C:\Users\yyd\Downloads
    file: BookWorm.log
  level:
    root: WARN
    org.springframework.security: DEBUG
a:
  b: i'm in github
